name: End-to-end tests
on: push
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Decrypt GPG file
        run: |
          gpg --quiet --batch --yes --decrypt --passphrase="${{ secrets.PASSWORD }}" --output E:/AUTOMATION TRAINING/automationApi/cypress/fixtures/credentials.json E:/AUTOMATION TRAINING/automationApi/cypress/fixtures/credentials.json.gpg
          shell: /usr/bin/bash -e {0}
          env:
          PASSWORD: ${{ secrets.PASSWORD }}
          usage: gpg [options] --decrypt [credentials.json.gpg]
      # Install npm dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v5
